config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
require 'httparty'

class Recipe < ApplicationRecord
  include HTTParty
  #key_value = "31c388c0c5f859983f4ea332128f6fd2"
  key_value = ENV['FOOD2FORK_KEY']
  hostport = ENV["FOOD2FORK_SERVER_AND_PORT"] || "www.food2fork.com"
  base_uri "http://#{hostport}/api"
  default_params key: key_value
  format :json

  def self.for (keyword)
    get("/search", query: {q: keyword})["recipes"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  	if !params[:search].nil?
  	else
  		params[:search] = ""
  	end
  	@recipes = Recipe.for(params[:search])
  end
end

#  class RecipesController < ApplicationController
#   def index
#     @search_term = params[:search] || "chocolate"
#     @recipes_found = Recipe.for(@search_term)
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<hr>
	<small>
		<a href="https://recipehunter-f2f.herokuapp.com/">RecipeHunter</a> by 
    	<a href="https://ayushexploring.github.io" target="_blank">Ayush Verma</a>
	</small>
</footer>
<br>

app/views/layouts/_header.html.erb
<header>
	<div>
		<br>
		<h2 align="center"><b>Welcome to RecipeHunter</b></h2>
		<h4 align="center">Created by <a href="https://ayushexploring.github.io" target="_blank">Ayush Verma</a></h4>
		<h5 align="center">Powered By Food2Fork.com</h5>
		<br>
	</div>
	<div id="temp">
		<div id="home-btn">
			<a href="https://recipehunter-f2f.herokuapp.com"><button class="btn btn-success">Home</button></a>
		</div>
		<div id="recipe-search">
			<%= form_tag recipes_index_path, method: :get, id: 'search' do %>
				<%= text_field_tag :search , '', placeholder: 'Search Recipe by ingredient' , :required => true %>
				<%= submit_tag "Search", class: 'btn btn-success' %>
			<% end %>
		</div>
	</div><br>
	<p>Food2Fork is an ever expanding recipe website. It strives to bring people closer by being able share your favorite meals and recipes with everyone around the world. By combining ingredients and title search, Food2Fork makes finding recipes easy. Food2Fork recipes are from everyday cooks and chefs that have perfected the recipe over time. Food2Fork recipes range from the decadent to the simple for whatever mood you are in. With recipes being added daily there will alway be something new for you to crave.</p>
	<br>
</header>	

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeHunter</title>
    <%= render 'layouts/rails_default' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/recipes/index.html.erb
<% unless params[:search].nil? %>
	<div>
		<% if !params[:search].empty? %>
			<h4>Results for <%= params[:search] %> (<%= @recipes.count %>)</h4>
		<% else %>
			<h4>Check out some of our top Recipes</h4>
		<% end %>
		<hr>
		<!-- <table class="table table-striped">
			<thead class="black white-text" class="black">
			  <tr>
			  	<th scope="col">#</th>
			  	<th scope="col">Recipe</th>
			  	<th scope="col">Title</th>
			  	<th scope="col">Publisher</th>
			  	<th scope="col">Social Rank</th>
			  </tr>
			</thead>
			<tbody>
			  <% x = 0 %>
			  <% @recipes.each do |recipe| %>
			    <tr>
			    	<th scope="row"><%= x+= 1 %></th>
			      	<td id="image"><%= link_to(image_tag(recipe["image_url"]), recipe['f2f_url'])%></td>
			      	<td><%= link_to(sanitize(recipe["title"]), recipe['f2f_url']) %></td>
			      	<td><%= link_to(sanitize(recipe["publisher"]), recipe['publisher_url']) %></td>
			      	<td><%= recipe["social_rank"] %></td>
			    </tr>
			  <% end %>
			</tbody>
		</table> -->
		<div class="parent">
			<% @recipes.each do |recipe| %>
				<div class="card">
		  			<%= link_to(image_tag(recipe["image_url"]), recipe['f2f_url'], target: :_blank)%>
		  			<div class="container"><br>
		    			<p><b>Title: <%= link_to(sanitize(recipe["title"]), recipe['f2f_url'], target: :_blank) %></b></p>
		    			<p><b>Publisher:
		    			<%= link_to(sanitize(recipe["publisher"]), recipe['publisher_url'], target: :_blank) %>
		    			</b></p>
		    			<p><b>Social Rank: <%= recipe["social_rank"] %></b></p>
		  			</div>
				</div>
			<% end %>
		</div>
	</div>
<% end %>